
export const PASSWORD_HASHER = Symbol('PASSWORD_HASHER');

export const REGISTRATION_REPOSITORY = Symbol('REGISTRATION_REPOSITORY');

export const LOGIN_REPOSITORY = Symbol('LOGIN_REPOSITORY');

export const SESSION_TOKEN_PROVIDER = Symbol('SESSION_TOKEN_PROVIDER');